### ISSUE TITLE
ShuffleMatrix随机概率有问题

### ISSUE THREAD

**Issue by songzhibin97** [golang-infrastructure/go-shuffle#1]
m * n 的矩阵项
```
1       2       3       4       
5       6       7       8       
9       10      11      12
```
在收缩的过程中例如到下标7 概率就和预期的不一致
```
1       2       3       x
5       6      7       x
x       x       x       x      
```

**Comment by CC11001100** [comment]
一种可能的修复方案： 
1. 在逻辑上认为是把矩阵打平的，认为其多行是拼接到一起的，则问题转换为和一维数组shuffle一致，需要引入几个变量辅助梳理这个问题，比如用limit限制随机数生成的范围，初始化limit = n*m，在[0, limit]之间选择一个随机数与当前limit位置的数字做交换，此后交换一个limit就往前走一步，limit-1，不需要重复初始化limit
2. 将[0, limit]之间选中的数字称之为n，则实际选中的元素是矩阵中下标为[n/columns, n%columns]的元素，limit所在的下标可以通过两层i--, j--的for循环来定位，所以不需要显示声明
4. 上面的假设是基于数组的每一行右侧都是对齐的，因此需要先进行参数检查，方法签名加个error
